### ISSUE TITLE
Installation fails on ubuntu 14.04

### ISSUE THREAD

**Issue by sisoascg** [BloodAxe/CloudCV#3]
sudo npm install
/
> native-opencv@3.0.0 install /home/mahesh/CloudCVImpl/CloudCV/node_modules/cloudcv-backend/node_modules/native-opencv
> node installer.js

Loading OpenCV from  http://static.computer-vision-talks.com/dist/opencv/opencv-3.0.0-unix.zip
     fetch : http://static.computer-vision-talks.com/dist/opencv/opencv-3.0.0-unix.zip
  progress : [====================] 100% 0.0s

File downloaded successfully!

> cloudcv-backend@1.0.1 install /home/mahesh/CloudCVImpl/CloudCV/node_modules/cloudcv-backend
> node-gyp rebuild

make: Entering directory `/home/mahesh/CloudCVImpl/CloudCV/node_modules/cloudcv-backend/build'
  CXX(target) Release/obj.target/cloudcv/src/cloudcv.o
  CXX(target) Release/obj.target/cloudcv/src/framework/marshal/marshal.o
  CXX(target) Release/obj.target/cloudcv/src/framework/marshal/stl.o
In file included from ../src/framework/marshal/stl.cpp:2:0:
../src/framework/Logger.h:43:1: warning: "/*" within comment [-Wcomment]
 /*
 ^
../src/framework/marshal/stl.cpp: In function ‘bool MarshalToNative(V8Result, std::string&)’:
../src/framework/marshal/stl.cpp:17:47: warning: ‘int NanAsciiString::Size() const’ is deprecated (declared at ../node_modules/nan/nan.h:1229) [-Wdeprecated-declarations]
         outVal = std::string(*cStr, cStr.Size());
                                               ^
  CXX(target) Release/obj.target/cloudcv/src/framework/marshal/opencv.o
In file included from ../src/framework/marshal/node_object_builder.hpp:7:0,
                 from ../src/framework/marshal/opencv.cpp:2:
../src/framework/Logger.h:43:1: warning: "/*" within comment [-Wcomment]
 /*
 ^
  CXX(target) Release/obj.target/cloudcv/src/framework/marshal/primitives.o
  CXX(target) Release/obj.target/cloudcv/src/framework/marshal/node_object_builder.o
In file included from ../src/framework/marshal/node_object_builder.hpp:7:0,
                 from ../src/framework/marshal/node_object_builder.cpp:1:
../src/framework/Logger.h:43:1: warning: "/*" within comment [-Wcomment]
 /*
 ^
  CXX(target) Release/obj.target/cloudcv/src/framework/Image.o
In file included from ../src/framework/NanCheck.hpp:14:0,
                 from ../src/framework/Image.cpp:3:
../src/framework/Logger.h:43:1: warning: "/*" within comment [-Wcomment]
 /*
 ^
In file included from ../node_modules/nan/nan.h:74:0,
                 from ../src/framework/Image.hpp:5,
                 from ../src/framework/Image.cpp:1:
../node_modules/nan/nan_new.h: In instantiation of ‘typename NanIntern::Factory<T>::return_t NanNew(A0) [with T = v8::Integer; A0 = long unsigned int; typename NanIntern::Factory<T>::return_t = v8::Local<v8::Integer>]’:
../src/framework/Image.cpp:174:9:   required from here
../node_modules/nan/nan_new.h:209:41: error: call of overloaded ‘New(long unsigned int&)’ is ambiguous
   return NanIntern::Factory<T>::New(arg0);
                                         ^
../node_modules/nan/nan_new.h:209:41: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:194:0,
                 from ../node_modules/nan/nan.h:74,
                 from ../src/framework/Image.hpp:5,
                 from ../src/framework/Image.cpp:1:
../node_modules/nan/nan_implementation_pre_12_inl.h:125:1: note: static NanIntern::IntegerFactory<T>::return_t NanIntern::IntegerFactory<T>::New(int32_t) [with T = v8::Integer; NanIntern::IntegerFactory<T>::return_t = v8::Local<v8::Integer>; int32_t = int]
 IntegerFactory<T>::New(int32_t value) {
 ^
In file included from ../node_modules/nan/nan.h:74:0,
                 from ../src/framework/Image.hpp:5,
                 from ../src/framework/Image.cpp:1:
../node_modules/nan/nan_new.h:110:26: note: static NanIntern::IntegerFactory<T>::return_t NanIntern::IntegerFactory<T>::New(uint32_t) [with T = v8::Integer; NanIntern::IntegerFactory<T>::return_t = v8::Local<v8::Integer>; uint32_t = unsigned int]
   static inline return_t New(uint32_t value);
                          ^
In file included from ../node_modules/nan/nan.h:74:0,
                 from ../src/framework/Image.hpp:5,
                 from ../src/framework/Image.cpp:1:
../node_modules/nan/nan_new.h: In function ‘typename NanIntern::Factory<T>::return_t NanNew(A0) [with T = v8::Integer; A0 = long unsigned int; typename NanIntern::Factory<T>::return_t = v8::Local<v8::Integer>]’:
../node_modules/nan/nan_new.h:210:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/framework/Image.cpp: In static member function ‘static v8::Handle<v8::Value> cloudcv::ImageView::AsJpegStream(const v8::Arguments&)’:
../src/framework/Image.cpp:196:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/framework/Image.cpp: In static member function ‘static v8::Handle<v8::Value> cloudcv::ImageView::AsPngStream(const v8::Arguments&)’:
../src/framework/Image.cpp:217:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/framework/Image.cpp: In static member function ‘static v8::Handle<v8::Value> cloudcv::ImageView::Thumbnail(const v8::Arguments&)’:
../src/framework/Image.cpp:253:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/framework/Image.cpp: In static member function ‘static v8::Handle<v8::Value> cloudcv::ImageView::AsPngDataUri(const v8::Arguments&)’:
../src/framework/Image.cpp:274:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/framework/Image.cpp: In static member function ‘static v8::Handle<v8::Value> cloudcv::ImageView::AsJpegDataUri(const v8::Arguments&)’:
../src/framework/Image.cpp:347:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/framework/Image.cpp: In function ‘v8::Handle<v8::Value> cloudcv::loadImage(const v8::Arguments&)’:
../src/framework/Image.cpp:426:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
make: *** [Release/obj.target/cloudcv/src/framework/Image.o] Error 1
make: Leaving directory `/home/mahesh/CloudCVImpl/CloudCV/node_modules/cloudcv-backend/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-27-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mahesh/CloudCVImpl/CloudCV/node_modules/cloudcv-backend
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! cloudcv-backend@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cloudcv-backend@1.0.1 install script.
npm ERR! This is most likely a problem with the cloudcv-backend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cloudcv-backend
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-27-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/mahesh/CloudCVImpl/CloudCV
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by BloodAxe** [comment]
Aknowledge. Need to update C++ bindings to work nice with new NaN library.

**Comment by BloodAxe** [comment]
As a temporary fix I made a dirty hack to cast size_t to uint32_t. When this issue will be resolved I will put it back: https://github.com/rvagg/nan/issues/270.

**Comment by sisoascg** [comment]
I am still facing the below error with the latest code , can you please tell me if I am doing something wrong here : 
npm install 
npm ERR! git fetch -a origin (git://github.com/BloodAxe/CloudCVBackend.git) fatal: Could not read from remote repository.
npm ERR! git fetch -a origin (git://github.com/BloodAxe/CloudCVBackend.git) 
npm ERR! git fetch -a origin (git://github.com/BloodAxe/CloudCVBackend.git) Please make sure you have the correct access rights
npm ERR! git fetch -a origin (git://github.com/BloodAxe/CloudCVBackend.git) and the repository exists.
npm ERR! Error: Command failed: fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Socket.<anonymous> (child_process.js:969:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/mahesh/CloudCVImpl/CloudCV
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mahesh/CloudCVImpl/CloudCV/npm-debug.log
npm ERR! not ok code 0

**Comment by BloodAxe** [comment]
Recently I installed CloudCV on new hosting and it worked fine. Your log indicates a connection problem of some sort. Perhaps you can try again to see if it helps. I will close this issue since problem with NaN module has been resolved. If another problem exists, please feel free to open new issue.

**Comment by sisoascg** [comment]
Thanks a lot , I am able to build, the problem was with the proxy settings, I am able to install now, thanks for your quick response
